In [1]:
import numpy as np


In [16]:
def perceptron(data, labels, params = {}, hook = None):    
    # if T not in params, default to 100
    T = params.get('T', 100)
    # Your implementation here
    d, n = data.shape
    theta = np.zeros((d,1)) 
    print("theta = " , theta)
     
    misclassified = np.zeros((n,1))
    count = 0
    theta_0 = np.zeros(1)
    #print("d = {}, n = {}, theta shape = {}, theta_0 shape = {}".format(d,n,theta.shape,theta_0.shape))
  
    for t in range(T):     
      for i in range(n):
        y = labels[0,i]
        x = data[:,i]
        
        a = np.dot(x,theta)+theta_0
        
        if np.sign(y*a) <=0: # update the thetas
          theta[:,0] = theta[:,0]+ y*x
          theta_0 = theta_0 + y
          misclassified[i][0] += 1
          count += 1
        #print(theta, theta_0)
          
    #print("shape x = {}, y = {}, theta = {}, theta_0 = {}".format(x.shape,y.shape,theta.shape,theta_0.shape))
    #print( "times misclassified = ", misclassified )
    print("count = ", count)
    return (theta,np.array([theta_0]))
        
          

In [5]:
def averaged_perceptron(data, labels, params = {}, hook = None):    
    # if T not in params, default to 100
    T = params.get('T', 100)
    print(T)
    # Your implementation here
    d, n = data.shape
    theta = np.zeros((d,1)) 
    theta_s = np.zeros((d,1)) 
     
    misclassified = np.zeros((n,1))
    count = 0
    theta_0 = np.zeros(1)
    theta_0_s = np.zeros(1)
    print("d = {}, n = {}, theta shape = {}, theta_0 shape = {}".format(d,n,theta.shape,theta_0.shape))
  
    for t in range(T):     
      for i in range(n):
        y = labels[0,i]
        x = data[:,i]
        
        a = np.dot(x,theta)+theta_0
        #print("a = {}".format(a))
        positive = np.sign(y*a)
        
        if np.sign(y*a) <=0: # update the thetas
          theta[:,0] = theta[:,0]+ y*x
          theta_0 = theta_0 + y
          misclassified[i][0] += 1
          count += 1
        theta_s[:,0] += theta[:,0]
        theta_0_s += theta_0
        #print(theta, theta_0)
          
    print("shape x = {}, y = {}, theta = {}, theta_0 = {}".format(x.shape,y.shape,theta.shape,theta_0.shape))
    #print( "times misclassified = ", misclassified )
    print("count = ", count)
    return (theta_s/(n*T),np.array([theta_0_s])/(n*T))
        
          

In [17]:
#data = np.array([[1,0,-1.5],[-1,1,-1]])

#data = np.array([[1,-1],[0,1],[-1.5,-1]]).T
#data = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]).T
data = np.array([[-1,1],[1,-1],[1,1],[2,2]]).T
labels = np.array([[1,1,-1,-1]])

print(data)
print(labels)

p = perceptron(data, labels, params = {}, hook = None)

print(perceptron(data, labels, params = {}, hook = None))

[[-1  1  1  2]
 [ 1 -1  1  2]]
[[ 1  1 -1 -1]]
theta =  [[0.]
 [0.]]
count =  3
theta =  [[0.]
 [0.]]
count =  3
(array([[-1.],
       [-1.]]), array([[1.]]))


In [ ]:
A = np.array([[1,0,-1.5],[-1,1,-1]])
print(A)
print(A/10)

In [ ]:
def positive(x, th, th0):
    return np.sign((np.dot(th.T,x)+th0)/np.sqrt(np.dot(th.T,th)))

def score(data, labels, th, th0):
    A = (positive(data,th,th0)==labels)
    return np.sum(A)

def eval_classifier(learner, data_train, labels_train, data_test, labels_test):
    theta, theta_0 = learner(data_train, labels_train)
    return score(data_test,labels_test,theta,theta_0)/len(labels_test[0])

In [ ]:
def eval_learning_alg(learner, data_gen, n_train, n_test, it):
    eval = 0
    for i in range(it):
        data_train, labels_train = data_gen(n_train)
        data_test, labels_test = data_gen(n_test)
        eval += eval_classifier(learner, data_train, labels_train, data_test, labels_test)
    return eval/it


In [ ]:
def xval_learning_alg(learner, data, labels, k):
  n = len(data[0])  

  num_slice1 = n%k
  slice1 = n//k + 1
  num_slice2 = k - n%k 
  slice2 = n//k
  eval = 0
  print(slice1)
  print(num_slice1)

  for i in range(num_slice1):
    D_test = data[: , i*slice1:(i+1)*slice1 ]
    labels_test = labels[: , i*slice1:(i+1)*slice1 ]
    D_train = np.concatenate((data[: , 0:i*slice1], data[: , (i+1)*slice1:]), axis=1) 
    labels_train = np.concatenate((labels[: , 0:i*slice1], labels[: , (i+1)*slice1:]), axis=1)

    print(np.shape(D_test))
    print(np.shape(labels_test))
    print(np.shape(D_train))
    print(np.shape(labels_train))

    eval += eval_classifier(learner, D_train, labels_train, D_test, labels_test)

  for i in range(num_slice2):
    D_test = data[: , i*slice2:(i+1)*slice2 ]
    labels_test = labels[: , i*slice2:(i+1)*slice2 ]
    D_train = np.concatenate((data[: , 0:i*slice2], data[: , (i+1)*slice2:]), axis=1) 
    labels_train = np.concatenate((labels[: , 0:i*slice2], labels[: , (i+1)*slice2:]), axis=1)

    print(np.shape(D_test))
    print(np.shape(labels_test))
    print(np.shape(D_train))
    print(np.shape(labels_train))

    eval += eval_classifier(learner, D_train, labels_train, D_test, labels_test)

  return eval/(num_slice1+num_slice2)


In [ ]:
data  = np.array([[1,2],[3,4],[5,6],[7,8]]).T
labels = np.array([[1,1,1,-1]])

print(xval_learning_alg(perceptron, data, labels, 4))

In [ ]:
n = 20
k = 3
print(n%k*(n//k+1) + (n//k)*(k - n%k))

In [218]:
def gen_lin_separable(num_points=20, th=np.array([[3],[4]]), th_0=np.array([[0]]), dim=2):
    ''' 
    Generate linearly separable dataset X, y given theta and theta0
    Return X, y where
    X is a numpy array where each column represents a dim-dimensional data point
    y is a column vector of 1s and -1s
    '''
    X = np.random.uniform(low=-5, high=5, size=(dim, num_points))
    y = np.sign(np.dot(np.transpose(th), X) + th_0)
    return X, y


def gen_flipped_lin_separable(num_points=20, pflip=0.25, th=np.array([[3],[4]]), th_0=np.array([[0]]), dim=2):
    '''
    Generate difficult (usually not linearly separable) data sets by
    "flipping" labels with some probability.
    Returns a method which takes num_points and flips labels with pflip
    '''
    def flip_generator(num_points=20):
        X, y = gen_lin_separable(num_points, th, th_0, dim)
        flip = np.random.uniform(low=0, high=1, size=(num_points,))
        for i in range(num_points):
            if flip[i] < pflip: y[0,i] = -y[0,i]
        return X, y
    return flip_generator

In [266]:
X,y = gen_flipped_lin_separable(20, 0.1, np.array([[3],[4]]), np.array([[0]]), 2)(20)
print(X)
print(y)
sum = 0
#edited eval_learning_alg according to last part of assignement
def eval_learning_alg(learner, data_gen, n_train, n_test, it):
    eval = 0
    for i in range(it):
        data_train, labels_train = data_gen(n_train)
        data_test, labels_test = data_gen(n_test)
        eval += eval_classifier(learner, data_train, labels_train, data_train, labels_train)
    return eval/it

for i in range(10):
    sum += eval_learning_alg(perceptron,gen_flipped_lin_separable(200, 0.25, np.array([[3],[4]]), np.array([[0]]), 2), 20, 20, 100)
print(sum/10)

[[-3.73578205  1.7545927  -3.98548298 -0.40536267 -3.70868489  3.29810922
   0.50321422  1.91756076 -3.15360755  0.38926433  0.85355075 -1.26807321
   2.22450961  2.88192426 -0.69842901 -0.2427011  -3.0267915   2.32503859
   3.00319102 -2.60940483]
 [-2.54410467  0.79214628 -0.11462798  1.32540431 -1.80810363 -1.06558946
  -1.43389213  3.22590225  3.81030468  4.66312238 -0.98847698  1.59141838
  -4.37840281 -1.96489432 -2.16079477  4.58117471 -0.75792844 -4.79920886
  -1.03140278  2.20728432]]
[[-1.  1. -1.  1. -1.  1. -1.  1.  1.  1. -1. -1.  1.  1. -1.  1. -1.  1.
   1.  1.]]
count =  788
count =  839
count =  930
count =  881
count =  485
count =  1009
count =  637
count =  929
count =  1064
count =  1095
count =  722
count =  781
count =  1073
count =  692
count =  669
count =  1094
count =  906
count =  1027
count =  706
count =  854
count =  732
count =  1004
count =  641
count =  410
count =  768
count =  584
count =  938
count =  719
count =  682
count =  580
count =  782
count

In [ ]:
def eval_learning_alg(learner, data_gen, n_train, n_test, it):
    eval = 0
    for i in range(it):
        data_train, labels_train = data_gen(n_train)
        data_test, labels_test = data_gen(n_test)
        eval += eval_classifier(learner, data_train, labels_train, data_train, labels_train)
    return eval/it
