In [2]:
import numpy as np	

def signed_dist(x,th,th0):
    return (np.dot(th.T,x)+th0)/np.sqrt(np.dot(th.T,th))

x = np.array([[1],[2],[3]])

th = np.array([[1],[1],[1]])

th0 = +20

print( signed_dist(x,th,th0) )


[[15.011107]]


In [3]:
import numpy as np	

def positive(x,th,th0):
    return np.sign((np.dot(th.T,x)+th0))

x = np.array([[1,2],[2,3],[3,4]])

th = np.array([[1,2,3],[1,2,3],[1,2,3]])

th0 = -0.5
print(positive(x,th,th0))

print(np.dot(th.T,x)+th0)




[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[ 5.5  8.5]
 [11.5 17.5]
 [17.5 26.5]]


In [4]:
data = np.transpose(np.array([[1, 2], [1, 3], [2, 1], [1, -1], [2, -1]]))
#labels = rv([-1, -1, +1, +1, +1])
th = np.array([[1],[1]])
th0 = -10
print(data)
A  = positive(data,th,th0)
print(A)


[[ 1  1  2  1  2]
 [ 2  3  1 -1 -1]]
[[-1 -1 -1 -1 -1]]


In [5]:
labels = np.array([np.array([-1, -1, +1, +1, +1])])
#so we have 5 2D data points
#and we have a hyperplane given by 1, 2D vec
data = np.transpose(np.array([[1, 2], [1, 3], [2, 1], [1, -1], [2, -1]]))
th = np.array([[1],[1]])
th0 = np.array([-2])
A = (positive(data,th,th0)==labels)
print(A)




[[False False  True False False]]


In [6]:
def score(data,labels,th,th0):
    A = (positive(data,th,th0)==labels)
    return (np.array([np.sum(A,axis=1).tolist()]))

ths = np.array([[1,2],[1,2]])
th0s = np.array([np.array([100,+-1])])    

print(np.argmax(score(data,labels,ths,th0s)))
print((score(data,labels,ths,th0s)))
print(np.shape(score(data,labels,ths,th0s)))

A = np.dot(ths.T,data)


#print(labels)
#print(positive(data,th,th0))

ValueError: operands could not be broadcast together with shapes (2,5) (1,2) 

In [7]:
def best_seperator(data, labels, ths, th0s):
    A = (positive(data,ths,th0s)==labels)
    return ths.T[np.argmax((np.array([np.sum(A,axis=1).tolist()])))],th0s[np.argmax((np.array([np.sum(A,axis=1).tolist()])))]

A = best_seperator(data,labels,ths,th0s)

print(A)

    

ValueError: operands could not be broadcast together with shapes (2,5) (1,2) 

In [8]:
import numpy as np

ths = np.array([[1,2],[1,2]])
th0s = np.array([np.array([100,+-1])])  
data = np.transpose(np.array([[1, 2], [1, 3], [2, 1], [1, -1], [2, -1]]))
labels = np.array([np.array([-1, -1, +1, +1, +1])])

#print(ths,th0s,data,labels)

def score(data, labels, th, th0):
    A = (positive(data,th,th0.T)==labels)
    return np.sum(A,axis=1).tolist()

#print(score(data,labels,ths,th0s))

def best_separator(data, labels, ths, th0s):
    scores = score(data, labels, ths, th0s)
    best_arg = np.argmax(scores)
    
    return  np.transpose(ths[best_arg]), np.array([np.array([th0s[0][best_arg]])])
    # return ths.T[np.argmax((np.array([np.sum(A,axis=1).tolist()])))],th0s[np.argmax((np.array([np.sum(A,axis=1).tolist()])))]




B = best_seperator(data,labels,ths,th0s)

print(B[0])
print(np.shape(B[0]))




ValueError: operands could not be broadcast together with shapes (2,5) (1,2) 

In [9]:
a = np.array([[1],[2]])
b = np.array([[1]])


def test(a,b):
    a = a.T
    return a,b

print(test(a,b)[0])

[[1 2]]
